---
abstract: 'Plack Timing Statistics Middleware'
author:
  - 'Dai Okabayashi <bayashi@cpan.org>'
build_requires:
  Capture::Tiny: 0
  HTTP::Request::Common: 0
  Plack::Builder: 0
  Plack::Test: 0
  Test::More: 0.88
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-TimeStats
provides:
  Plack::Middleware::TimeStats:
    file: lib/Plack/Middleware/TimeStats.pm
    version: 0.01
requires:
  Devel::TimeStats: 0.03
  Plack::Middleware: 0
  Plack::Util::Accessor: 0
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bayashi/Plack-Middleware-TimeStats
version: 0.01
